# Default configuration for orgctl
# https://huggins.dev/orgctl

path: "~/orgfiles/"
default-title: "untitled"
filename-template: "{{.ID}}-{{slugify .Title}}"
content-template: ""

group:
  journal:
    path: "journal/"
    default-title: '{{now | date "2006"}}-{{now | date "01"}}-{{now | date "02"}}'
    filename-template: '{{now | date "2006"}}/{{now | date "01"}}/{{now | date "02"}}'
    content-template: |
      #+title: {{now | date "2006"}}-{{now | date "01"}}-{{now | date "02"}}
      #+filetags: :journal:

tools:
  editor: ""
